### ISSUE TITLE
Access to Oyez API

### ISSUE THREAD

**Issue by davebiagioni** [walkerdb/supreme_court_transcripts#1]
Thanks for this very cool work!  I had two questions I was hoping you could help me with:

1. How did you generate the `case_summaries.json` file?  Is there a single API call?
2. Speaking of APIs, how did you get access to the Oyez API?  I haven't had any luck finding documentation on this via web search.

Thanks in advance for your time.

**Comment by walkerdb** [comment]
Hi! Thanks for reaching out! Also this was a good reminder for me to update the readme with some API info...

I believe the API is all undocumented, but this is the gist as far as I was able to tell when I grabbed this data last May:

All case summaries (this retrieves the equivalent of the case_summaries.json file): 
`https://api.oyez.org/cases?per_page=0`

If you don't want everything you can add a term filter, like the following:
`https://api.oyez.org/cases?per_page=0&filter=term:1965`

That data will hold links to get further info on each case. eg:
`https://api.oyez.org/cases/1965/14_orig`

The format here is generally `api.oyez.org/cases/{term}/{docket_number}`

The "oral_argument_audio" field in this case-specific response holds links to the audio and transcriptions for each hearing - this data is what is saved in the transcription files in the repo. eg:
`https://api.oyez.org/case_media/oral_argument_audio/14026`

It's a little embarrasing but you can see the kinda hacky code I originally put together to scrape this data in this commit: https://github.com/walkerdb/supreme_court_transcripts/commit/21f50514ba89f1989178af7b0ccb93528272ad92 .

Hope that helps!

**Comment by davebiagioni** [comment]
Excellent, thanks much!!!
