### ISSUE TITLE
Other court transcripts

### ISSUE THREAD

**Issue by ghost** [walkerdb/supreme_court_transcripts#5]
This is awesome. Any plans for other court transcript bulk data, or might anyone know of a similar project doing that?

**Comment by azeemba** [comment]
#4 actually has some information about the CourtListener project. They have opinions and audio files of courts at many different levels (state and federal). 

Their GitHub repo has an issue where they are investigating auto-transcription but I don't think they have finished that feature yet.

**Comment by ghost** [comment]
Thank you! I've heard of court listener, but didn't know they kept audio. I wonder whether there are plans to upload written transcripts.

**Comment by azeemba** [comment]
https://github.com/freelawproject/courtlistener/issues/440 is the issue I was referring to

**Comment by ghost** [comment]
Thanks! Going to follow this one closely and see if I can contribute!
